name: 'Verify conventional commit'
description: 'Check that last commit follows the conventional commit rules'
inputs:
  github_commit:
    description: 'latest github commit'
    required: true
  commit_title:
    description: 'title of latest commit'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_commit }}
